[package]
name = "Camilla"
version = "0.1.0"
edition = "2021"
authors = ["me"]

[lib]
name = "libcamilla"
path = "src/libcamilla/lib.rs"

[[bin]]
name = "camilla"
path = "src/main.rs"

[dependencies]
bitvec = "1.0.1"
